version: '3.9'
services:
  awsglue:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    ports:
    - 4040:4040
    - 18080:18080
    - 8998:8998
    - 8888:8888
    environment:
      # <<: *spark-env
      AWS_PROFILE: default
      DISABLE_SSL: true 
      DATALAKE_FORMATS: hudi,iceberg
    volumes:
    - "~/.aws:/home/glue_user/.aws"
    - "./workspace/:/home/glue_user/workspace/"
    - "./workspace/jupyter_workspace/:/home/glue_user/workspace/jupyter_workspace/"
    command: ["/home/glue_user/jupyter/jupyter_start.sh"]
    networks:
      - oss_gharchivedata_orchestration_airflow_default

networks:
  oss_gharchivedata_orchestration_airflow_default:
    external: true
